package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boxDaoConfig;
    private final DaoConfig exerciseSetDaoConfig;

    private final BoxDao boxDao;
    private final ExerciseSetDao exerciseSetDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boxDaoConfig = daoConfigMap.get(BoxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        exerciseSetDaoConfig = daoConfigMap.get(ExerciseSetDao.class).clone();
        exerciseSetDaoConfig.initIdentityScope(type);

        boxDao = new BoxDao(boxDaoConfig, this);
        exerciseSetDao = new ExerciseSetDao(exerciseSetDaoConfig, this);

        registerDao(Box.class, boxDao);
        registerDao(ExerciseSet.class, exerciseSetDao);
    }
    
    public void clear() {
        boxDaoConfig.getIdentityScope().clear();
        exerciseSetDaoConfig.getIdentityScope().clear();
    }

    public BoxDao getBoxDao() {
        return boxDao;
    }

    public ExerciseSetDao getExerciseSetDao() {
        return exerciseSetDao;
    }

}
