package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXERCISE_SET.
 */
public class ExerciseSet {

    private Long id;
    private Integer duration;
    private java.util.Date date;
    private String exercise;
    private String muscle;
    private Double weight;
    private Integer reps;

    public ExerciseSet() {
    }

    public ExerciseSet(Long id) {
        this.id = id;
    }

    public ExerciseSet(Long id, Integer duration, java.util.Date date, String exercise, String muscle, Double weight, Integer reps) {
        this.id = id;
        this.duration = duration;
        this.date = date;
        this.exercise = exercise;
        this.muscle = muscle;
        this.weight = weight;
        this.reps = reps;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getExercise() {
        return exercise;
    }

    public void setExercise(String exercise) {
        this.exercise = exercise;
    }

    public String getMuscle() {
        return muscle;
    }

    public void setMuscle(String muscle) {
        this.muscle = muscle;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Integer getReps() {
        return reps;
    }

    public void setReps(Integer reps) {
        this.reps = reps;
    }

}
